### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by clavijojuan** [geoffcfchen/webRTC-react-native-firebase-expo#3]
Hi,

Great implementation of webRTC React Native expo plugin.

Can u implement some example with latest version of expo. react native,  and react-native-webrtc ?

**Comment by ega65** [comment]
Hi, It is not very difficult.. ..I've done it, but the code is quite now intricated in my new development to publish it.. :s 

If I remember well, I had just changed the versions on my package.json like 

"dependencies": {
    "@config-plugins/react-native-webrtc": "^6.0.0",
    "@expo/config-plugins": "~6.0.0",
....
    "expo": "^48.0.17",
...
    "expo-dev-client": "~2.2.1",
    "expo-device": "~5.2.1",
....
    "firebase": "^9.22.0",
....
    "react": "18.2.0",
    "react-dom": "18.2.0",
...
    "react-native": "0.71.8",
.....
    "react-native-web": "~0.18.7",
    "react-native-webrtc": "^1.106.1",
  },

I hope it helps more than it confuses... ;)

**Comment by clavijojuan** [comment]
> Hi, It is not very difficult.. ..I've done it, but the code is quite now intricated in my new development to publish it.. :s
> 
> If I remember well, I had just changed the versions on my package.json like
> 
> "dependencies": { "@config-plugins/react-native-webrtc": "^6.0.0", "@expo/config-plugins": "~6.0.0", .... "expo": "^48.0.17", ... "expo-dev-client": "~2.2.1", "expo-device": "~5.2.1", .... "firebase": "^9.22.0", .... "react": "18.2.0", "react-dom": "18.2.0", ... "react-native": "0.71.8", ..... "react-native-web": "~0.18.7", "react-native-webrtc": "^1.106.1", },
> 
> I hope it helps more than it confuses... ;)

Yeah it works. Thanks !!
